name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Wait for MongoDB to be ready
        run: |
          until docker-compose exec -T mongo mongosh --eval 'db.runCommand({ ping: 1 })'; do
            echo "Waiting for MongoDB to be ready..."
            sleep 5
          done

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies for client
        run: |
          cd src/client
          npm ci

      - name: Install dependencies for server
        run: |
          cd src/server
          npm ci

      - name: Run linter for client
        run: |
          cd src/client
          npm run lint

      - name: Run linter for server
        run: |
          cd src/server
          npm run lint

      - name: Run backend tests
        run: |
          cd src/server
          npm test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}

      - name: Stop services with Docker Compose
        run: docker-compose down