name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies for client
        run: |
          cd src/client
          npm ci

      - name: Install dependencies for server
        run: |
          cd src/server
          npm ci

      - name: Run linter for client
        run: |
          cd src/client
          npm run lint

      - name: Run linter for server
        run: |
          cd src/server
          npm run lint