name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: "--health-cmd='mongo --eval \"db.runCommand({ ping: 1 })\"' --health-interval=10s --health-timeout=5s --health-retries=5"

    steps:
      - name: Sleep for MongoDB readiness
        run: sleep 30

      - name: Install MongoDB CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-clients

      - name: Wait for MongoDB
        run: |
          for i in {1..30}; do
            if echo "db.runCommand({ ping: 1 })" | mongo localhost:27017/test --quiet; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB to be ready..."
            sleep 2
          done
          echo "MongoDB did not start in time."
          exit 1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies for client
        run: |
          cd src/client
          npm ci

      - name: Install dependencies for server
        run: |
          cd src/server
          npm ci

      - name: Run backend tests
        run: |
          cd src/server
          npm test
        env:
          MONGO_URL: ${{ secrets.TEST_MONGODB_URI }}
